#连接数据库
spring:
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  30MB
      # 设置总上传的文件大小
      max-request-size:  50MB

datasource:
  username: root
  password: 111
  url: jdbc:mysql://43.142.146.167:3306/db?useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  driver-class-name: com.mysql.cj.jdbc.Driver
  #数据源用druid
  type: com.alibaba.druid.pool.DruidDataSource
  #数据源其他配置
  initialSize: 5
  minIdle: 5
  maxActive: 20
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 1 FROM DUAL
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true

  # redis 配置
  redis:
    database: 2
    iddatabase: 2
    host: 43.142.146.167
    lettuce:
      pool:
        max-active: 8 #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8 #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0 #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
    password: "2222"
    port: 6379




#mybatis:
#  #全局配置文件
#  config-location: classpath:mybatis/mybatis-config.xml
#  #mapper配置文件
#  mapper-locations: classpath:mybatis/mapper/*.xml

mybatis-plus:
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    enable-sql-runner: true
    db-config:
      id-type: ASSIGN_ID
  mapper-locations: classpath*:com/yb/**/mapper/**/*.xml

logging:
  config: classpath:logback-spring.xml